Clock countdown
1Iv4N/flutter.dev-website pull request #5
Opened 2019-10-22 17:00 UTC by GomezMimo

## Clock Countdown
Shows a countdown for flutter event.

## Staging link
https://huge-flutter-dev-qa.firebaseapp.com/clock

## Screenshot image
![image](https://user-images.githubusercontent.com/3761030/67310408-4e3e0c00-f4c3-11e9-8666-d78701673d1f.png)

2019-10-23 04:38 UTC, 1Iv4N requested changes
Please review the 320px breakpoint, it looks like is broken.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +    animation: slide-in 0.8s;
Remove leading cero.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +      animation-delay: 0s;
Remove unit.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +      animation-delay: 0.2s;
Remove leading cero. Please, review all definitions.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_showcase.scss
>  .showcase {
Why are we editing showcase styles?

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_variables.scss
> +$flutter-color-dark-blue: #232C33;
Careful! You're overriding an existing variable.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/image/clock/left_rectangle-medium.svg
> +<?xml version="1.0" encoding="UTF-8"?><svg width="322" height="560" xmlns="http://www.w3.org/2000/svg"><path d="M-178 2h497.7v556.2H-178z" stroke="#62B2F4" stroke-width="2.7" fill="none" fill-rule="e
I think we should be able to reuse the same image and resize it as necessary. Please, review and apply to all images tagged as large, medium and small.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/js/countdown.js
> +    const eventTime = moment('21-12-2019 17:30:00', 'DD-MM-YYYY HH:mm:ss');
Why are we using the time 17:30?

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/js/countdown.js
> +            const duration = moment.duration(eventTime.diff(currentTime));
Initially, I thought we would need more complex operations. I think we can do this without using an external library. My bad, sorry!

2019-10-23 04:38 UTC, 1Iv4N commented on src/_includes/head.html
> +  {% endif %}
A copule of comments:
- In general, is not a good idea to add conditionals like this to the code. If you read carefully, line 41 solves the same problem. You just need to define a `js` key-value in the page's front matter.
- If we'll use an external library is usually a good idea to use Google's CDN. The bad news is that moment.js is not available, fortunately, we can go without it. :)

2019-10-23 04:38 UTC, 1Iv4N commented on src/_layouts/base.html
> +    {% endif %}
Same comment regarding the `if` statement. Check `src/_includes/banner.html`, we could do something like that. Is better to add a key-value to the `_config.yml` file.

2019-10-23 04:38 UTC, 1Iv4N commented on src/clock/index.html
> +        {% asset clock/oval-small.svg class='svg-animated svg-animated--oval svg-animated--small' %}
Taking into account that we could reduce some repeated files. I think it would be better to include all figures as background images.

2019-10-23 04:38 UTC, 1Iv4N commented on src/clock/index.html
> +        </div>
I think we can just keep the `h1` and merge some styles.

2019-10-23 04:38 UTC, 1Iv4N commented on src/clock/index.html
> +        </div>
Can we make this cleaner and avoid so much nesting?

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +    height: 24px;
Avoid declaring element's height, favor font-size, line-height, and margin.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +    animation: slide-in 1s 0.8s;
Remove leading cero.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +      animation-delay: 0.4s;
Remove leading cero.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +      animation-delay: 0.6s;
Remove leading cero.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +    animation-timing-function: cubic-bezier(0.87, 1.15, 1, 0.99);
Remove leading cero.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +      }
It looks like this is not necessary.

2019-10-23 04:38 UTC, 1Iv4N commented on src/_assets/css/_clock.scss
> +      }
It looks like this is not necessary.

2019-10-23 16:54 UTC, GomezMimo commented on src/_assets/css/_variables.scss
> +$flutter-color-dark-blue: #232C33;
Yes, my bad, thanks.

2019-10-23 16:55 UTC, GomezMimo commented on src/_assets/css/_showcase.scss
>  .showcase {
There are some styles that can be shared in the clock and showcase, that's why I took the opportunity to change it.

2019-10-23 21:24 UTC, GomezMimo commented on src/_assets/js/countdown.js
> +    const eventTime = moment('21-12-2019 17:30:00', 'DD-MM-YYYY HH:mm:ss');
It's just an example while we get the actual date of the event.

2019-11-01 14:45 UTC, 1Iv4N commented
@OmarGM2294 will create a new PR.

2019-11-01 14:45 UTC, closed without merging